In [1]:
import pandas as pd
import os

In [7]:
mainpath="/home/leoda/Descargas/"
filename="conectiwidad-wifi.csv"
fullpath = os.path.join(mainpath, filename)

In [13]:
red = pd.read_csv(fullpath)
red.tail()

,id,identificador,ubicacion,latitud,longitud,municipio_id,provincia_id,id_departamento,municipio,provincia,departamento
884,190,SAL048-01,Salta - Municipalidad,-24.805356,-65.421924,SAL048,AR-A,1681.0,Salta,Salta,Capital
885,94,BUE120-01,Plaza Balcarce,-34.769098,-59.686758,BUE120,AR-B,1315.0,Suipacha,Buenos Aires,Suipacha
886,211,BUE091-01,Punto Digital,-40.785915,-63.000000,BUE091,AR-B,1286.0,Patagones,Buenos Aires,Patagones
887,215,CBA012-01,SUM Municipal,-32.234565,-62.884633,CBA012,AR-X,1384.0,Alto Alegre,C칩rdoba,Union
888,71,BUE075-01,OPENDOOR (Plaza),-34.491083,-59.075778,BUE075,AR-B,1270.0,Luj치n,Buenos Aires,Lujan

In [14]:
red.dtypes

id                   int64
identificador       object
ubicacion           object
latitud            float64
longitud           float64
municipio_id        object
provincia_id        object
id_departamento    float64
municipio           object
provincia           object
departamento        object
dtype: object

In [15]:
red.describe()

                id     latitud    longitud  id_departamento
count   889.000000  889.000000  889.000000       873.000000
mean    645.168729  -24.309570  -45.547245      1462.088202
std     406.346018   15.635890   28.114595       148.840080
min       1.000000  -54.869533  -72.882993      1195.000000
25%     253.000000  -34.715680  -64.378778      1336.000000
50%     650.000000  -31.290480  -59.075778      1441.000000
75%    1012.000000    0.000000    0.000000      1586.000000
max    1349.000000    0.000000    0.000000      1723.000000